# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 623)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(700, 470, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 161, 211))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 41, 16))
        self.label.setObjectName("label")
        self.comboBox_uart = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_uart.setGeometry(QtCore.QRect(60, 30, 87, 22))
        self.comboBox_uart.setObjectName("comboBox_uart")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 51, 20))
        self.label_2.setObjectName("label_2")
        self.comboBox_baud = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_baud.setGeometry(QtCore.QRect(60, 60, 87, 22))
        self.comboBox_baud.setObjectName("comboBox_baud")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_databit = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_databit.setGeometry(QtCore.QRect(60, 90, 87, 22))
        self.comboBox_databit.setObjectName("comboBox_databit")
        self.comboBox_databit.addItem("")
        self.comboBox_databit.addItem("")
        self.comboBox_databit.addItem("")
        self.comboBox_databit.addItem("")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 51, 20))
        self.label_3.setObjectName("label_3")
        self.comboBox_polarity = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_polarity.setGeometry(QtCore.QRect(60, 120, 87, 22))
        self.comboBox_polarity.setObjectName("comboBox_polarity")
        self.comboBox_polarity.addItem("")
        self.comboBox_polarity.addItem("")
        self.comboBox_polarity.addItem("")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 120, 51, 20))
        self.label_4.setObjectName("label_4")
        self.comboBox_stopbit = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_stopbit.setGeometry(QtCore.QRect(60, 150, 87, 22))
        self.comboBox_stopbit.setObjectName("comboBox_stopbit")
        self.comboBox_stopbit.addItem("")
        self.comboBox_stopbit.addItem("")
        self.comboBox_stopbit.addItem("")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 150, 51, 20))
        self.label_5.setObjectName("label_5")
        self.comboBox_flow = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_flow.setGeometry(QtCore.QRect(60, 180, 87, 22))
        self.comboBox_flow.setObjectName("comboBox_flow")
        self.comboBox_flow.addItem("")
        self.comboBox_flow.addItem("")
        self.comboBox_flow.addItem("")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 180, 51, 20))
        self.label_6.setObjectName("label_6")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 230, 161, 151))
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton.setGeometry(QtCore.QRect(10, 30, 61, 19))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_2.setGeometry(QtCore.QRect(90, 30, 61, 19))
        self.radioButton_2.setObjectName("radioButton_2")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox.setGeometry(QtCore.QRect(10, 60, 91, 19))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_2.setGeometry(QtCore.QRect(10, 90, 91, 19))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_3.setGeometry(QtCore.QRect(10, 120, 91, 19))
        self.checkBox_3.setObjectName("checkBox_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 390, 161, 141))
        self.groupBox_3.setObjectName("groupBox_3")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_3.setGeometry(QtCore.QRect(90, 30, 61, 19))
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_4.setGeometry(QtCore.QRect(10, 30, 61, 19))
        self.radioButton_4.setObjectName("radioButton_4")
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_4.setGeometry(QtCore.QRect(10, 60, 91, 19))
        self.checkBox_4.setObjectName("checkBox_4")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(10, 90, 51, 20))
        self.label_7.setObjectName("label_7")
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox.setGeometry(QtCore.QRect(50, 90, 91, 22))
        self.spinBox.setObjectName("spinBox")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(180, 10, 611, 421))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(180, 440, 511, 91))
        self.textBrowser_2.setObjectName("textBrowser_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_background = QtWidgets.QAction(MainWindow)
        self.action_background.setObjectName("action_background")
        self.action_ascii = QtWidgets.QAction(MainWindow)
        self.action_ascii.setObjectName("action_ascii")
        self.action_crc = QtWidgets.QAction(MainWindow)
        self.action_crc.setObjectName("action_crc")
        self.action_about = QtWidgets.QAction(MainWindow)
        self.action_about.setObjectName("action_about")
        self.action_start = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("image/start.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_start.setIcon(icon)
        self.action_start.setObjectName("action_start")
        self.action_pause = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("image/pause.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_pause.setIcon(icon1)
        self.action_pause.setObjectName("action_pause")
        self.action_exit = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("image/stop.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_exit.setIcon(icon2)
        self.action_exit.setObjectName("action_exit")
        self.action_clear = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("image/editclear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_clear.setIcon(icon3)
        self.action_clear.setObjectName("action_clear")
        self.action_font = QtWidgets.QAction(MainWindow)
        self.action_font.setObjectName("action_font")
        self.menu.addAction(self.action_start)
        self.menu.addAction(self.action_pause)
        self.menu.addAction(self.action_exit)
        self.menu.addAction(self.action_clear)
        self.menu_2.addAction(self.action_font)
        self.menu_2.addAction(self.action_background)
        self.menu_3.addAction(self.action_ascii)
        self.menu_3.addAction(self.action_crc)
        self.menu_4.addAction(self.action_about)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.toolBar.addAction(self.action_start)
        self.toolBar.addAction(self.action_pause)
        self.toolBar.addAction(self.action_exit)
        self.toolBar.addAction(self.action_clear)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "发送"))
        self.groupBox.setTitle(_translate("MainWindow", "串口设置"))
        self.label.setText(_translate("MainWindow", "串口"))
        self.label_2.setText(_translate("MainWindow", "波特率"))
        self.comboBox_baud.setItemText(0, _translate("MainWindow", "2400"))
        self.comboBox_baud.setItemText(1, _translate("MainWindow", "4800"))
        self.comboBox_baud.setItemText(2, _translate("MainWindow", "9600"))
        self.comboBox_baud.setItemText(3, _translate("MainWindow", "19200"))
        self.comboBox_baud.setItemText(4, _translate("MainWindow", "38400"))
        self.comboBox_baud.setItemText(5, _translate("MainWindow", "57600"))
        self.comboBox_baud.setItemText(6, _translate("MainWindow", "115200"))
        self.comboBox_baud.setItemText(7, _translate("MainWindow", "128000"))
        self.comboBox_baud.setItemText(8, _translate("MainWindow", "256000"))
        self.comboBox_baud.setItemText(9, _translate("MainWindow", "921600"))
        self.comboBox_databit.setItemText(0, _translate("MainWindow", "5"))
        self.comboBox_databit.setItemText(1, _translate("MainWindow", "6"))
        self.comboBox_databit.setItemText(2, _translate("MainWindow", "7"))
        self.comboBox_databit.setItemText(3, _translate("MainWindow", "8"))
        self.label_3.setText(_translate("MainWindow", "数据位"))
        self.comboBox_polarity.setItemText(0, _translate("MainWindow", "无"))
        self.comboBox_polarity.setItemText(1, _translate("MainWindow", "奇校验"))
        self.comboBox_polarity.setItemText(2, _translate("MainWindow", "偶校验"))
        self.label_4.setText(_translate("MainWindow", "校验位"))
        self.comboBox_stopbit.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_stopbit.setItemText(1, _translate("MainWindow", "1.5"))
        self.comboBox_stopbit.setItemText(2, _translate("MainWindow", "2"))
        self.label_5.setText(_translate("MainWindow", "停止位"))
        self.comboBox_flow.setItemText(0, _translate("MainWindow", "无"))
        self.comboBox_flow.setItemText(1, _translate("MainWindow", "RTS/CTS"))
        self.comboBox_flow.setItemText(2, _translate("MainWindow", "XON/XOFF"))
        self.label_6.setText(_translate("MainWindow", "流控"))
        self.groupBox_2.setTitle(_translate("MainWindow", "接收设置"))
        self.radioButton.setText(_translate("MainWindow", "ASCII"))
        self.radioButton_2.setText(_translate("MainWindow", "Hex"))
        self.checkBox.setText(_translate("MainWindow", "自动换行"))
        self.checkBox_2.setText(_translate("MainWindow", "显示发送"))
        self.checkBox_3.setText(_translate("MainWindow", "显示时间"))
        self.groupBox_3.setTitle(_translate("MainWindow", "发送设置"))
        self.radioButton_3.setText(_translate("MainWindow", "Hex"))
        self.radioButton_4.setText(_translate("MainWindow", "ASCII"))
        self.checkBox_4.setText(_translate("MainWindow", "重复发送"))
        self.label_7.setText(_translate("MainWindow", "时间"))
        self.menu.setTitle(_translate("MainWindow", "编辑"))
        self.menu_2.setTitle(_translate("MainWindow", "显示"))
        self.menu_3.setTitle(_translate("MainWindow", "工具"))
        self.menu_4.setTitle(_translate("MainWindow", "帮助"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.action_background.setText(_translate("MainWindow", "背景颜色"))
        self.action_ascii.setText(_translate("MainWindow", "ASCII"))
        self.action_crc.setText(_translate("MainWindow", "CRC"))
        self.action_about.setText(_translate("MainWindow", "关于"))
        self.action_start.setText(_translate("MainWindow", "开始"))
        self.action_pause.setText(_translate("MainWindow", "暂停"))
        self.action_exit.setText(_translate("MainWindow", "关闭"))
        self.action_clear.setText(_translate("MainWindow", "清屏"))
        self.action_font.setText(_translate("MainWindow", "字体"))
